
# CPU DATA
CPU_DATA_WARNING_GREATER_THAN = 80
CPU_DATA_WARNING_LESS_OR_EQUAL = 90

CPU_DATA_ERROR_GREATER_THAN = 90


# Memory DATA
MEMORY_DATA_WARNING_GREATER_THAN = 80
MEMORY_DATA_WARNING_LESS_OR_EQUAL = 90

MEMORY_DATA_ERROR_GREATER_THAN = 90


# Sensors DATA
SENSORS_BATTERY_DATA_WARNING_LESS_THAN = 30
SENSORS_BATTERY_DATA_WARNING_GREATER_OR_EQUAL = 20

SENSORS_BATTERY_DATA_ERROR_LESS_THAN = 20

# Remove comment if needed
"""
SENSORS_SEC_LEFT_DATA_WARNING_LESS_THAN = 1200
SENSORS_SEC_LEFT_DATA_WARNING_GREATER_OR_EQUAL = 600

SENSORS_SEC_LEFT_DATA_ERROR_LESS_THAN = 600
"""


# Disk DATA
DISK_DATA_WARNING_GREATER_THAN = 80
DISK_DATA_WARNING_LESS_OR_EQUAL = 90

DISK_DATA_ERROR_GREATER_THAN = 90


# # CPU DATA
# CPU_DATA_WARNING_GREATER_THAN = 1
# CPU_DATA_WARNING_LESS_OR_EQUAL = 2
#
# CPU_DATA_ERROR_GREATER_THAN = 2
